amadeus/urls.py
from django.urls import path
from .views import PatientSearchView


app_name = 'amadeus'


urlpatterns = [
    path('', PatientSearchView.as_view(), name='patient-search'),
]

orion/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('amadeus/', include('amadeus.urls', namespace='amadeus')),
]

amadeus/models.py
from django.db import models

# Create your models here.

amadeus/forms.py
from django import forms


class RequestForm(forms.Form):
    GENDER_CHOICES = [('male', 'Male'),
                      ('female', 'Female')]
    surname = forms.CharField(
        max_length=50,
        required=True,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Surname'
        }))
    gender = forms.ChoiceField(
        choices=GENDER_CHOICES,
        required=True,
        widget=forms.RadioSelect(attrs={'class': 'form-check-input'})
        )

amadeus/views.py
from django.shortcuts import render
from django.views.generic import FormView
from .forms import RequestForm
from .utils import OrionHealthAPI

# Create your views here.


class PatientSearchView(FormView):
    form_class = RequestForm
    template_name = 'amadeus/search_patient.html'

    def form_valid(self, form):
        gender = form.cleaned_data['gender']
        surname = form.cleaned_data['surname']
        patient = OrionHealthAPI().\
            get_patient(surname, gender)
        response_dct = {
            'success': render(self.request, 'amadeus/patient_info.html', {'patient': patient}),
            'undefined': render(self.request, 'amadeus/callback_page.html'),
            'unsuccessful': render(self.request, 'amadeus/unsuccessful_page.html')
        }
        return response_dct[patient['status']]

amadeus/templates/amadeus/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} Orion Amadeus {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'amadeus/css/styles.css' %}">
</head>
<body>
<div class="container">

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'amadeus:patient-search' %}">Orion</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="#">Extra</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    {% block content %}
        Lorem Ipsum Dolor Set Amet
    {% endblock %}
</div>
</body>
</html>

amadeus/templates/amadeus/callback_page.html
{% extends 'amadeus/base.html' %}


{% block title %} No matches, Oops! {% endblock %}

{% block content %}
    <br>
    <div class="alert alert-info" role="alert">
        No matches, Try again!
    </div>

    <a class="btn btn-primary" href="{% url 'amadeus:patient-search' %}" role="button">Search again</a>
{% endblock %}

amadeus/templates/amadeus/patient_info.html
{% extends 'amadeus/base.html' %}


{% block title %} PatientInfo {% endblock %}

{% block content %}
    <br>
    <div class="col-5">
        <div class="alert alert-primary" role="alert">
            Patient Info
        </div>
        {% for k, v in patient.items %}
            {% if k == 'address' %}
                <strong>{{ k }}</strong>: {% for i in v %} {{ i }}, {% endfor %}
            {% else %}
                <strong>{{ k }}</strong>: {{ v }}<br>
            {% endif %}
        {% endfor %}
        <br>
        <a class="btn btn-primary" href="{% url 'amadeus:patient-search' %}" role="button">Search again</a>
    </div>

{% endblock %}

amadeus/templates/amadeus/search_patient.html
{% extends 'amadeus/base.html' %}

{% block title %} Patient Search {% endblock %}

{% block content %}
    <div class="col-5">
        <h3>Set Parameters: </h3>
        <div class="form-group">
            <form method="post">
                {% csrf_token %}
                {{ form.surname }}
                {{ form.gender }}
                <br>
                <br>
                <br>
                <button type="submit" class="btn btn-primary">Search</button>
            </form>
        </div>
    </div>
{% endblock %}

amadeus/templates/amadeus/unsuccessful_page.html
{% extends 'amadeus/base.html' %}


{% block title %} Error Page {% endblock %}

{% block content %}

    <br>
    <div class="alert alert-danger" role="alert">
        Oops, Something goes wrong! Try again later!
    </div>

{% endblock %}